name: Test Devcontainer Feature

on:
  pull_request:
    paths:
      - "devcontainer-features/**"
      - ".github/workflows/test-devcontainer-feature.yml"
  push:
    branches:
      - main
    paths:
      - "devcontainer-features/**"
      - ".github/workflows/test-devcontainer-feature.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-defaults:
    name: Test defaults (${{ matrix.base_image }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base_image:
          - debian:12
          - mcr.microsoft.com/devcontainers/base:debian
    steps:
      - uses: actions/checkout@v4

      - name: Install devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Test course-md defaults
        working-directory: devcontainer-features
        run: devcontainer features test --skip-scenarios -f course-md --base-image ${{ matrix.base_image }} .

  test-scenarios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Test course-md scenarios
        working-directory: devcontainer-features
        run: devcontainer features test --skip-autogenerated -f course-md .